export default Object.freeze({
  WELCOME: 'Welcome',
  REGISTER: 'Register',
  LOGIN: 'Login',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  PRODUCT_DETAIL: 'ProductDetail',
  PRODUCT: 'Product',
  CART: 'Cart',
  SEARCH: 'Search',
  ACCOUNT: 'Account',
  PROFILE: 'Profile',
  ORDERS: 'Orders',
  ORDER_DETAIL: 'OrderDetail',
  ORDER_PRODUCT_DETAIL: 'OrderProductDetail',
  PROMO_ALERT: 'PromoAlert',
  CONTACT_US: 'ContactUs',
  ABOUT_US: 'AboutUs',
});
